name = "advent_of_code_2024"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gladvent = ">= 2.0.2 and < 3.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 0.14.1 and < 1.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
gleam_deque = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[gladvent.2024.1]
pt_1 = 1222801
pt_2 = 22545250

[gladvent.2024.2]
pt_1 = 326
pt_2 = 381

[gladvent.2024.3]
pt_1 = 174336360
pt_2 = 88802350

[gladvent.2024.4]
pt_1 = 2591
pt_2 = 1880

[gladvent.2024.5]
pt_1 = 4281
pt_2 = 5466

[gladvent.2024.6]
pt_1 = 5453
pt_2 = 2188

[gladvent.2024.7]
pt_1 = 663613490587
pt_2 = 110365987435001

[gladvent.2024.8]
pt_1 = 278
pt_2 = 1067

[gladvent.2024.9]
pt_1 = 6353658451014
pt_2 = 6382582136592

[gladvent.2024.10]
pt_1 = 737
pt_2 = 1619

[gladvent.2024.11]
pt_1 = 189167
pt_2 = 225253278506288

[gladvent.2024.12]
pt_1 = 1494342
pt_2 = 1206

[gladvent.2024.13]
pt_1 = 27105
pt_2 = 101726882250942

[gladvent.2024.14]
pt_1 = 211773366
pt_2 = 7344
